In [1]:
import numpy as np

In [2]:
s = 5 # scalar

In [3]:
v = np.array([5,-2,4]) # vector
v

array([ 5, -2,  4])

In [5]:
m = np.array([[5,12,6],
             [-3,0,14]]) # matrix
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
type(s)

int

In [7]:
type(m)

numpy.ndarray

In [8]:
s_array = np.array(5) # makes this an array too

In [9]:
# Data Shape - checks dimensionality
m.shape

(2, 3)

In [10]:
v.shape

(3,)

In [11]:
s_array.shape

()

In [12]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [13]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [14]:
# tensors - generalization
# scalar is rank 0 tensor
# vector is rank 1 tensor
# matrix is rank 2 tensor
# n-dArray is rank 3 tensor

# creating a tensor out of two matrices
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [15]:
m1


array([[ 5, 12,  6],
       [-3,  0, 14]])

In [16]:
t = np.array([m1,m2]) # this is a tensor
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [18]:
t.shape

(2, 2, 3)

In [19]:
t_manual_creation = np.array([[[ 5, 12,  6],
        [-3,  0, 14]],
       [[ 9,  8,  7],
        [ 1,  3, -5]]])
t_manual_creation

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [20]:
# adding matrices
m3 = m1 + m2
m3

array([[14, 20, 13],
       [-2,  3,  9]])

In [21]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [24]:
m1 = m1 + 1

In [25]:
m1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [26]:
m1 = m1 -1

In [28]:
# Transpose
# means transpose column vector to row vector
A = np.array([[5,12,6],[-3,0,14]])

In [29]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [30]:
# can only transpose vectors if you reshape into a (n,1) matrix instead of (n,) matrix

In [31]:
# Vector Multiplication
# Dot Product(iter product)
# Multiply each corresponding element and add their sum
# Multiply two vectors and you get a scalar(or a dot)
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [32]:
np.dot(x,y)

-66

In [33]:
# Dot Product of Matrices
A = np.array([[5,12,6],[-3,0,14]])
A*3

array([[15, 36, 18],
       [-9,  0, 42]])

In [34]:
# Can only multiply m*n matrix with n*k matrix
# [m*n] * [n*k] = [m*k]
B = np.array([[2,-1], [8,0], [3,0]])

In [36]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [38]:
x = np.array([1.2,-3])
y = np.array([2,3])
np.dot(x,y)

-6.6